import type { Metadata } from "next";

import Icons from "@/components/ui/Icons";
import Header from "@/components/layout/header";

import "@/styles/globals.css";
import { iranYekan, CubeFontIcon } from "@/styles/fonts";
import StoreProvider from "@/lib/store/provider";

export const metadata: Metadata = {
  title: "Digikala Next App",
  description: "Generated by Zakiye",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={`${iranYekan.className} ${CubeFontIcon.className}`}>
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
        <Icons />
      </body>
    </html>
  );
}
